# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50eb4d15553c25075f81a0a03957d71b4218b4865a8b060ac527c1877cc5163fefbcfc4a8ef1f5e37b935c6d491e9fdd9bbf4031e2761beed60a5fc1aea87600

test:
  secret_key_base: ef8ea3013edc292282fad74c4159c47bd45999147d18f9edd0a616f015e6a33a101f9f4c52b7538e25d767a58c037999e0e896f1480ab4e05e2c15a260d92164

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
